apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense

  # deployment resources label
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
      
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
      - name: nginx
        image: dhanushboga/backend:1.0.0
        resources:
     # soft limit
          requests:
            memory: 128Mi
            cpu: 100m

      # hard limit
          limits:
            memory: 128Mi
            cpu: 100m
        ports:
        - containerPort: 80


---

kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:  #labels are used as selectors
    app: backend
    tier: backend
    project: expense
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080
    

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15